apiVersion: apps/v1
kind: Deployment
metadata:
  name: cisa-kev-ingestion
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: cisa-kev-ingestion
          imagePullPolicy: Never
          env:
            - name: ENVIRONMENT
              value: local-dev
