apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: local-dev

resources:
  - ../../base

images:
  - name: ghcr.io/itsbriany/riskstream
    newName: riskstream
    newTag: local
  - name: ghcr.io/itsbriany/cisa-kev-ingestion
    newName: cisa-kev-ingestion
    newTag: local
  - name: ghcr.io/itsbriany/threatfox-ingestion
    newName: threatfox-ingestion
    newTag: local

patches:
  - path: patch.yaml
  - path: minio-patch.yaml
  - path: cisa-kev-ingestion-patch.yaml
  - path: threatfox-ingestion-patch.yaml
