apiVersion: apps/v1
kind: Deployment
metadata:
  name: threatfox-ingestion
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: threatfox-ingestion
          imagePullPolicy: Never
          env:
            - name: ENVIRONMENT
              value: local-dev
            - name: DEBUG_MODE
              value: "false"
            - name: DEBUG_PORT
              value: "5678"
