apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: riskstream
  namespace: argocd
spec:
  description: Riskstream GitOps project
  sourceRepos:
    - https://github.com/itsbriany/riskstream.git
    - https://grafana.github.io/helm-charts
    - https://fluent.github.io/helm-charts
  destinations:
    - namespace: main
      server: https://kubernetes.default.svc
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
