apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: riskstream
  namespace: argocd
spec:
  description: Riskstream GitOps project
  sourceRepos:
    - https://github.com/r0kit-sec/riskstream.git
  destinations:
    - namespace: staging
      server: https://kubernetes.default.svc
    - namespace: production
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"