apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: riskstream-staging
  namespace: argocd
spec:
  project: riskstream
  source:
    repoURL: https://github.com/r0kit-sec/riskstream.git
    targetRevision: main
    path: k8s/overlays/staging
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true