apiVersion: apps/v1
kind: Deployment
metadata:
  name: riskstream
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: riskstream
          imagePullPolicy: IfNotPresent
          env:
            - name: ENVIRONMENT
              value: production