apiVersion: v1
kind: Service
metadata:
  name: cisa-kev-ingestion
  labels:
    app: cisa-kev-ingestion
spec:
  selector:
    app: cisa-kev-ingestion
  ports:
    - name: http
      port: 80
      targetPort: http
