apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml
  - minio-deployment.yaml
  - minio-service.yaml
  - minio-init-job.yaml
  - cisa-kev-ingestion-deployment.yaml
  - cisa-kev-ingestion-service.yaml
  - cisa-kev-catalog-ingestion-cronjob.yaml
  - threatfox-ingestion-deployment.yaml
  - threatfox-ingestion-service.yaml
  - threatfox-recent-ingestion-cronjob.yaml
  - urlhaus-ingestion-deployment.yaml
  - urlhaus-ingestion-service.yaml
  - urlhaus-recent-ingestion-cronjob.yaml

configMapGenerator:
  - name: minio-init-scripts
    files:
      - init-minio-buckets.sh=scripts/init-minio-buckets.sh

commonLabels:
  app.kubernetes.io/name: riskstream
