apiVersion: apps/v1
kind: Deployment
metadata:
  name: urlhaus-ingestion
  labels:
    app: urlhaus-ingestion
spec:
  replicas: 1
  selector:
    matchLabels:
      app: urlhaus-ingestion
  template:
    metadata:
      labels:
        app: urlhaus-ingestion
    spec:
      containers:
        - name: urlhaus-ingestion
          image: ghcr.io/itsbriany/urlhaus-ingestion:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8083
              name: http
          env:
            - name: PORT
              value: "8083"
            - name: ENVIRONMENT
              value: "production"
            - name: URLHAUS_AUTH_KEY
              valueFrom:
                secretKeyRef:
                  name: urlhaus-secret
                  key: auth-key
                  optional: true
            - name: S3_ENDPOINT
              value: "minio:9000"
            - name: S3_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-user
            - name: S3_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-secret
                  key: root-password
            - name: S3_USE_SSL
              value: "false"
          readinessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /healthz
              port: http
            initialDelaySeconds: 10
            periodSeconds: 20
