apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: staging

resources:
  - ../../base

namePrefix: stg-

images:
  - name: ghcr.io/r0kit-sec/riskstream
    newName: ghcr.io/r0kit-sec/riskstream
    newTag: main

patches:
  - path: patch.yaml