apiVersion: apps/v1
kind: Deployment
metadata:
  name: riskstream
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: riskstream
          imagePullPolicy: Always
          env:
            - name: ENVIRONMENT
              value: staging